version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: budgy_DB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: budgy_dev
      POSTGRES_USER: budgy
      POSTGRES_PASSWORD: budgy
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    name: db_data
